# MCP Server Configuration for Cache Management System - Lite Version

# Global MCP Configuration
global:
  # Server settings
  host: "localhost"
  port: 8080
  protocol: "http"
  
  # Connection settings
  max_connections: 50
  request_timeout: 30
  enable_ssl: false
  
  # Authentication
  auth_enabled: false
  api_key: null
  
  # Logging
  log_level: "INFO"
  log_file: "./logs/mcp_servers_lite.log"
  enable_access_logs: true

# Cache MCP Server Configuration
cache_mcp_server:
  enabled: true
  name: "Cache MCP Server Lite"
  description: "Lightweight cache management system"
  
  # Server settings
  host: "localhost"
  port: 8080
  protocol: "http"
  
  # Connection settings
  max_connections: 50
  request_timeout: 30
  enable_ssl: false
  
  # Authentication
  auth_enabled: false
  api_key: null
  
  # Tools configuration (core tools only)
  tools:
    - name: "cache_get"
      description: "Get a value from the cache"
      parameters:
        - name: "key"
          type: "string"
          required: true
          description: "Cache key to retrieve"
        - name: "layer"
          type: "string"
          required: false
          description: "Specific cache layer to use"
    
    - name: "cache_set"
      description: "Store a value in the cache"
      parameters:
        - name: "key"
          type: "string"
          required: true
          description: "Cache key"
        - name: "value"
          type: "any"
          required: true
          description: "Value to store"
        - name: "layer"
          type: "string"
          required: false
          description: "Specific cache layer to use"
        - name: "ttl_seconds"
          type: "integer"
          required: false
          description: "Time-to-live in seconds"
    
    - name: "cache_delete"
      description: "Delete a value from the cache"
      parameters:
        - name: "key"
          type: "string"
          required: true
          description: "Cache key to delete"
        - name: "layer"
          type: "string"
          required: false
          description: "Specific cache layer to use"
    
    - name: "cache_stats"
      description: "Get overall cache statistics"
      parameters: []
    
    - name: "cache_clear"
      description: "Clear the cache"
      parameters:
        - name: "layer"
          type: "string"
          required: false
          description: "Specific cache layer to clear"

# Database Configuration
database:
  # PostgreSQL settings
  host: "localhost"
  port: 5432
  database: "paddle_plugin_cache"
  username: "postgres"
  password: "2001"
  ssl_mode: "prefer"
  
  # Connection pooling
  connection_pool:
    max_size: 10
    min_size: 2
    timeout: 30
    max_overflow: 10
  
  # Persistence
  persist_dir: "./cache_storage"
  
  # Collections (tables) - simplified
  collections:
    - name: "predictive_cache"
      description: "Predictive cache entries"
      columns:
        - name: "id"
          type: "uuid"
          primary_key: true
        - name: "key"
          type: "varchar(255)"
          not_null: true
          unique: true
        - name: "value"
          type: "jsonb"
          not_null: true
        - name: "metadata"
          type: "jsonb"
        - name: "created_at"
          type: "timestamp"
          not_null: true
        - name: "expires_at"
          type: "timestamp"
        - name: "access_count"
          type: "integer"
          default: 0
    
    - name: "semantic_cache"
      description: "Semantic cache entries"
      columns:
        - name: "id"
          type: "uuid"
          primary_key: true
        - name: "key"
          type: "varchar(255)"
          not_null: true
          unique: true
        - name: "value"
          type: "jsonb"
          not_null: true
        - name: "embedding"
          type: "vector(384)"
        - name: "metadata"
          type: "jsonb"
        - name: "created_at"
          type: "timestamp"
          not_null: true
        - name: "expires_at"
          type: "timestamp"
        - name: "access_count"
          type: "integer"
          default: 0
    
    - name: "vector_cache"
      description: "Vector cache entries"
      columns:
        - name: "id"
          type: "uuid"
          primary_key: true
        - name: "key"
          type: "varchar(255)"
          not_null: true
          unique: true
        - name: "value"
          type: "jsonb"
          not_null: true
        - name: "embedding"
          type: "vector(1536)"
        - name: "metadata"
          type: "jsonb"
        - name: "created_at"
          type: "timestamp"
          not_null: true
        - name: "expires_at"
          type: "timestamp"
        - name: "access_count"
          type: "integer"
          default: 0
    
    - name: "vector_diary"
      description: "Vector diary entries"
      columns:
        - name: "id"
          type: "uuid"
          primary_key: true
        - name: "session_id"
          type: "varchar(255)"
          not_null: true
        - name: "content"
          type: "text"
          not_null: true
        - name: "embedding"
          type: "vector(1536)"
        - name: "metadata"
          type: "jsonb"
        - name: "created_at"
          type: "timestamp"
          not_null: true
        - name: "expires_at"
          type: "timestamp"
        - name: "importance_score"
          type: "float"
          default: 0.0

# Integration Configuration
integration:
  # KiloCode routing
  kilocode_routing:
    enabled: true
    fallback_order: ["predictive", "semantic", "vector"]
    routing_logic: "simple"
  
  # MCP RAG Server
  mcp_rag_server:
    enabled: false
    endpoint: "http://localhost:8001"
    timeout: 30
  
  # Vector Store MCP
  vector_store_mcp:
    enabled: false
    endpoint: "http://localhost:8002"
    timeout: 30
  
  # Memory Bank Sync
  memory_bank_sync:
    enabled: false
    sync_interval: 600  # 10 minutes

# Performance Configuration
performance:
  # Cache settings - reduced for lite version
  cache_size_limits:
    predictive_cache: 500
    semantic_cache: 2000
    vector_cache: 1000
    vector_diary: 5000
  
  # TTL settings
  ttl_settings:
    predictive_cache: 1800  # 30 minutes
    semantic_cache: 43200   # 12 hours
    vector_cache: 3600      # 1 hour
    vector_diary: 604800    # 7 days
  
  # Cleanup settings
  cleanup_settings:
    enabled: true
    interval: 1800  # 30 minutes
    batch_size: 50
    max_workers: 2
  
  # Monitoring
  monitoring:
    enabled: true
    metrics_interval: 120  # seconds
    health_check_interval: 600  # 10 minutes
    alert_thresholds:
      response_time: 2000  # ms
      error_rate: 0.1      # 10%
      memory_usage: 0.9    # 90%
      cache_hit_rate: 0.5  # 50%

# Security Configuration
security:
  # Authentication
  authentication:
    enabled: false
    api_key: null
    jwt_secret: null
    token_expiry: 3600  # 1 hour
  
  # Rate limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 50
    burst_limit: 10
    window_size: 60  # seconds
  
  # CORS settings
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true
  
  # Input validation
  input_validation:
    enabled: true
    max_key_length: 255
    max_value_size: 5242880  # 5MB
    allowed_content_types: ["application/json", "text/plain"]

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # File logging
  file:
    enabled: true
    path: "./logs/cache_mcp_server_lite.log"
    max_size: 5242880  # 5MB
    backup_count: 3
    encoding: "utf-8"
  
  # Console logging
  console:
    enabled: true
    level: "INFO"
    format: "%(asctime)s - %(levelname)s - %(message)s"
  
  # Structured logging
  structured:
    enabled: false
    include_timestamp: true
    include_request_id: false
    include_user_id: false

# Development Configuration
development:
  debug_mode: false
  test_mode: false
  mock_data: false
  
  # Development database
  dev_database_url: "sqlite:///./cache_dev_lite.db"
  
  # Testing
  testing:
    test_timeout: 30
    test_parallelism: 2
    coverage_threshold: 0.6
  
  # Mock data settings
  mock_data_settings:
    num_mock_entries: 50
    mock_data_path: "./data/mock_data_lite.json"
  
  # Profiling
  profiling:
    enabled: false
    output_dir: "./profiles_lite"
    interval: 600  # seconds