version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://test_user:test_password@postgres:5432/test_db
      NODE_ENV: test
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run test:integration

  security-scanner:
    image: returntocorp/semgrep:latest
    volumes:
      - .:/src
    command: semgrep --config=auto /src

volumes:
  postgres_data:
